apiVersion: v1
kind: Pod
metadata:
  name: flight-app
  labels:
    app: flight-app
spec:
  containers:
    - name: flight-app
      image: julioborges05/flight-app-jvm:latest
      ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: flight-app-svc
spec:
  selector:
    app: flight-app
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer