apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  containers:
    - name: postgres
      image: 'postgres:latest'
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: quarkus
        - name: POSTGRES_USER
          value: quarkus
        - name: POSTGRES_DB
          value: quarkus
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: postgresql