apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-order-app
  labels:
    app: travel-order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-order-app
  template:
    metadata:
      labels:
        app: travel-order-app
    spec:
      containers:
        - name: travel-order-app
          image: julioborges05/travel-order-app-jvm:latest
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: travel-order-app-svc
spec:
  selector:
    app: travel-order-app
  ports:
    - port: 8083
      targetPort: 8083
  type: LoadBalancer